# Generated by Django 5.2.16 on 2026-07-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name_arabic', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('english_translation', models.CharField(default='', max_length=200)),
                ('number_of_ayahs', models.IntegerField()),
                ('revelation_type', models.CharField(max_length=20)),
            ],
        ),
    ]
