# Generated by Django 5.2.16 on 2026-08-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_color',
            field=models.CharField(default='#1A3C40', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_icon',
            field=models.CharField(default='🌙', max_length=10),
        ),
    ]
